server:
  port: 8085
spring:
  profiles:
    active: local
  application:
    name: trade-store
  datasource:
    url: jdbc:mysql://localhost:3306/tradedb
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  data:
    mongodb:
      uri: mongodb://localhost:27017/trade_history
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  redis:
    host: localhost           # or your Redis server hostname/IP
    port: 6379                # default Redis port
    password:                 # set if Redis is password-protected
    timeout: 5000             # connection timeout in milliseconds
    jedis:
      pool:
        max-active: 10        # max total connections
        max-idle: 8           # max idle connections
        min-idle: 2           # min idle connections
        max-wait: -1          # max wait time for connection in ms (-1 means infinite)
logging:
  level:
    org.springframework: INFO
